spring:
  application:
    name: API de contagem de pontos - PI
  profiles:
    active: dev
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/gestao_time_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
server:
  port: 8090
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/gestao_time_dev
---
spring:
  config:
    activate:
      on-profile: tst
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/gestao_time_tst
---
spring:
  config:
    activate:
      on-profile: prd
  datasource:
    url: jdbc:mysql://localhost:3306/gestao_time